services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mindy\Bundle\SeoBundle\:
        resource: '../../*'
        exclude: '../../{Model,Migrations,Tests,vendor}'

    Mindy\Bundle\SeoBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
